### ISSUE TITLE
我down了最新代码，在android上还是跑不起来

### ISSUE THREAD

**Issue by py389172739** [wangwei123/my-weex#2]
我的操作步骤大概是这样的：
第一种操作方式：
1.运行 npm run init
2.weexpack run android

第二种操作方式：
直接运行 weexpack run android
跑起来之后显示：
Network Error!
1.Make sure you use the command npm run serve launched local service
2.Make sure you modify your_current_ip to your local IP in WXMainActivity

我对比了一下与你更新前的区别，你在appframework中增加了一个Env.java文件，用于设置android端的启动文件的路径，我看生成的js文件不都是放在assets文件夹路径下，那路径不应该是相对于assets的路径吗？就像我们用navigator也跳转的时候，路径就是相对于assets的，但是我看到Env.java文件里是带ip的路径，为什么要用ip呢？

还有两个疑问：
第一个疑问：
你的init.js文件中的这部分：
`let indexURL = `http://${ip}:8080/dist/weex/App.js`
let androidIndexURL = argv._[0] === 'local' ? 'weex/App.js' : indexURL

// android 主机地址操作
let androidConfigFile = path.join(__dirname, '../platforms/android/appframework/src/main/java/com/alibaba/weex/constants/Env.java')
let androidConfig =
  `
package com.alibaba.weex.constants;

/**
 * Created by wangwei on 2017/4/18.
 */

public class Env {
    public static final String BUNDLE_URL = "${androidIndexURL}";
}

`

fs.writeFile(androidConfigFile, androidConfig, function (err) {
  if (err) {
    throw err
  }
  console.log('android写入INDEX_URL成功')
})
`
indexURL 是不是web端的首页url，而如果是android端的话就用‘weex/App.js’这个文件作为首页入口（运行npm run init的时候应该把‘weex/App.js’这个路径写到Env.java文件中），如果我理解没问题，那么这里的‘weex/App.js’是在assets中的，为什么不写成绝对路径呢? 而且我发现在中间其实还有一个dist文件夹，这样直接写‘weex/App.js’会不会找不到文件？

第二个疑问：
在android平台下的appframework下的Appconfig.java中有这么一部分：
`public static String getLaunchUrl() {
    if (isLaunchLocally()) {
      return sPreferences.getString("local_url", "file://assets/index.js");
    }
    return sPreferences.getString("launch_url", Env.BUNDLE_URL);
  }
`

这个isLaunchLocally方法从字面意思理解判断的是不是本地运行，那么你这个工程跑起来的时候我可不可以理解成本地运行呢？那getLaunchUrl理论上应该是返回return sPreferences.getString("local_url", "file://assets/index.js");
"local_url"  和  "launch_url" 分别在什么情况下生效呢？

**Comment by wangwei123** [comment]
你加一下我QQ吧，2531868871

**Comment by wangwei123** [comment]
只需要2步即可
1>    ./serve-start
2>    weexpack run android
